[package]
name = "physics"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
shared = { path = "../shared" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures-channel = "0.3.34"
wgpu = { version = "30.0.1", default-features = false, features = ["webgpu", "wgsl"] }
